### ISSUE TITLE
ErrorOutOfDeviceMemory on RADV Vulkan driver on a Radeon HD 7950

### ISSUE THREAD

**Issue by The-King-of-Toasters** [RippeR37/GL_vs_VK#2]
I am experiencing a problem where I cannot run tests 1 & 2 using the `vulkan-radeon` driver on Arch Linux. Both tests output the same error: 
`Caught runtime exception during test execution!`
`vk::CommandBuffer::end: ErrorOutOfDeviceMemory`

However this does not happen on test 3, which is showing an up to 100 fps improvement.

### My Specs
CPU: Intel i5-3570k
GPU: Radeon HD 7950 Boost
Vulkan Device:[ AMD RADV TAHITI](http://vulkan.gpuinfo.org/displayreport.php?id=1243)
OS: Arch Linux

### Extras
Output of [`glxinfo | grep version`](https://pastebin.com/4hdRaf0H)
Output of [`vulkaninfo`](https://pastebin.com/RHT4YAGF)

**Comment by RippeR37** [comment]
What kind of drivers do you have? Are you sure they are up-to-date? If yes, then I think there are two version of AMD drivers on Linux for Vulkan - open source and proprietary ones from AMD itself. Could you test on both? And please test on machine right after startup (with nothing in background).

This seems to be reporting out-of-device memory when building command buffer, which kinda explains why it fails on 1st and 2nd test (as they have bigger command buffers) but on the other hand it shouldn't have happened as it was tested on other devices with same amount of memory too and it worked there correctly. Hard to say but maybe you have some other apps in the background which takes a lot of VRAM?

Also, you can enable debug validation layers by changing line `GL_vs_VK/src/framework/VKTest.cpp` from `const bool kDebugEnabled = false;` to `const bool kDebugEnabled = true;` and see if it prints anything on your machine.

**Comment by The-King-of-Toasters** [comment]
I've edited the file and recompiled, unfortunately this also throws an error of its own: 
`Caught std::system_error!`
   `Code:    vk::Result:-6`
  `Message: vk::createInstance: ErrorLayerNotPresent`

I also cannot run the AMDGPU-PRO driver as it requires me to downgrade to kernel 4.9 and xorg 1.18, which I am not keen to do. 

As for current drivers, this is the result of `pacman -Q | egrep "vulkan|mesa"`:
`lib32-mesa-vdpau 17.1.1-1`
`lib32-vulkan-icd-loader 1.0.46.0-1`
`lib32-vulkan-radeon 17.1.1-1`
`lib32-vulkan-validation-layers 1.0.46.0-1`
`mesa 17.1.1-1`
`mesa-demos 8.3.0-2`
`mesa-vdpau 17.1.1-1`
`vulkan-headers 1:1.0.51-1`
`vulkan-icd-loader 1.0.46.0-1`
`vulkan-radeon 17.1.1-1`
`vulkan-trace 1.0.46.0-1`
`vulkan-validation-layers 1.0.46.0-1`

**Comment by RippeR37** [comment]
>Message: vk::createInstance: ErrorLayerNotPresent

This says, that you either don't have installed VulkanSDK or it's not found in your PATH/etc. Please visit [this webiste](https://vulkan.lunarg.com/doc/sdk/1.0.51.0/windows/getting_started.html) which should help you set it up. Without any debugging information I really can't help anyhow, as I don't own AMD GPU myself and I can't reproduce it in anyway.

Original error comes up due to lack of device memory when command buffer is recorded and since command buffers doesn't depend on any particular memory heap it's not that. It might be that driver does something in very unoptimized way and somehow fills it, or you are using some other applications which use Vulkan and shared memory resources. In second test I use only one PushConstant per frame, so it shouldn't be a problem and these buffers consists mostly of draw commands so that shouldn't take so much memory...
